### ISSUE TITLE
Remove unused dependency

### ISSUE THREAD

**Issue by Finderstein** [Veetaha/mipz-practice-1#1]
Having gone though all code, I don't see any usage of `cfg-if` library. Looks like it was added during development, but then it began unused.
You should remove it from `Cagro.toml` to reduce the binary code bloat.

https://github.com/Veetaha/mipz-practice-1/blob/c904cff7b3ba4955c9417b181ed3b1b809a6dc11/Cargo.toml#L13

**Comment by Veetaha** [comment]
Looks like an oversight, will remove it!
