### ISSUE TITLE
Move CLI args parsing to a separate module

### ISSUE THREAD

**Issue by Finderstein** [Veetaha/mipz-practice-1#3]
This code doesn't belong to `main.rs` file. According to Rust conventions, argument parsing should live separately from `main()` function.

https://github.com/Veetaha/mipz-practice-1/blob/c904cff7b3ba4955c9417b181ed3b1b809a6dc11/src/main.rs#L8-L19

**Comment by Veetaha** [comment]
Sure, this looks like a right conventional thing. Makes sense to do
