### ISSUE TITLE
Comments typo)

### ISSUE THREAD

**Issue by IanaKhitsko** [Veetaha/mipz-practice-1#8]
https://github.com/Veetaha/mipz-practice-1/blob/5384646b3c545b8e48f041f00aaf76fe03a351de/src/calc.rs#L129

surrounding?

**Comment by Veetaha** [comment]
That's an oversight, thanks, fixed

**Comment by IanaKhitsko** [comment]
It is still without double 'r'))

**Comment by Veetaha** [comment]
@IanaKhitsko good catch, fixed in a6959ceb5b92a0494330903db36cdbb9150e01f9
